from pydantic import BaseModel, Field
from typing import Optional, List, Dict, Any


# ─── Document processing ──────────────────────────────────────────────────────

class ProcessDocumentRequest(BaseModel):
    document_id: str
    user_id: str
    file_path: str


class ProcessDocumentResponse(BaseModel):
    document_id: str
    chunk_count: int
    text_chunk_count: int = 0
    image_chunk_count: int = 0
    status: str = "success"


# ─── RAG Chat ─────────────────────────────────────────────────────────────────

class ChatMessage(BaseModel):
    role: str  # "user" | "assistant"
    content: str


class TheoryChatRequest(BaseModel):
    user_id: str
    message: str
    session_id: str = "default"
    history: List[ChatMessage] = Field(default_factory=list)


class SourceChunk(BaseModel):
    document_id: str
    chunk_index: int
    content: str
    score: float
    is_builtin: bool = False   # True if from the built-in theory knowledge base
    source_type: str = "text"  # "text" | "image" — image chunks were generated by vision analysis
    page: Optional[int] = None


class TheoryChatResponse(BaseModel):
    answer: str
    sources: List[SourceChunk] = Field(default_factory=list)
    found_in_theory: bool
    session_id: str


# ─── Analysis output (Phase 2/3 placeholder types) ────────────────────────────

class EntryZone(BaseModel):
    from_price: float = Field(alias="from")
    to_price: float = Field(alias="to")

    class Config:
        populate_by_name = True


class TradeSetupOutput(BaseModel):
    symbol: str
    timeframe: str
    market_bias: str
    setup_type: str
    entry_condition: str
    entry_zone: Dict[str, float]
    stop_loss: float
    target1: float
    target2: float
    risk_reward: str
    position_size: int
    confidence_score: int
    rules_passed: List[str]
    rules_failed: List[str]
    theory_references: List[Dict[str, Any]]
    reasoning: str
    invalidation_condition: str
    risk_warning: str = "This is analysis only, not financial advice. Always confirm manually before trading."
